# Basic configs and environment variables
config:
  service: service-name
  region: ap-southeast-1
  userpool_authorizer_arn: ARN
  user_pool_id: POOL_ID
env:
  MONGODB_ATLAS_CLUSTER_URI: URI_FOR_MONGO
  BUCKET_NAME: bkt_prod
  BUCKET_REGION: ap-southeast-1
